### ISSUE TITLE
Use monaspace fonts 

### ISSUE THREAD

**Issue by Terkwood** [Terkwood/equanimity#84]
https://monaspace.githubnext.com/

eg (may need to strip vscode theming)

```css
/* Define a class for TerminalDimensions */
.terminal_dimensions {
  width: 999px;
  height: 999px;
  max-width: 999px;
  max-height: 999px;
}

/* Implement a timing animation */
@keyframes timing_m_ {
  0% {
    opacity: 0;
  }
  50% {
    opacity: .5;
  }
  100% {
    opacity: 1;
  }
}

/* Apply the animation */
.terminal_dimensions_w_ {
  animation-name: timing_m_;
  animation-duration: 9999ms;
}

/* Set a limit to the size of elements */
* {
  max-width: 999px;
  max-height: 999px;
}

/* Set the dimensions of body */
body {
  width: 100%;
  height: 100%;
}

/* Optimized layout with flex */
.flex_layout {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
```
